### ISSUE TITLE
Group of commands running in Python 3.7.6 Shell, but failing as Script file.

### ISSUE THREAD

**Issue by rosarion** [python/devguide#578]
```pycon
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from __future__ import absolute_import, division, print_function, unicode_literals
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> import tensorflow as tf
>>> from tensorflow import keras
>>> print(tf.__version__)
2.1.0
```

BUT IF I RUN THESE COMMANDS as a PYTHON SCRIPT FILE iy FAILS.
```pytb
======================== RESTART: D:\PythonCode-1\tmp.py =======================
Traceback (most recent call last):
  File "D:\PythonCode-1\tmp.py", line 7, in <module>
    import tensorflow as tf
  File "C:\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python.tools'; 'tensorflow.python' is not a package
>>> 
```

Why is it failing as a Script file ?
Is there something wrong in my Procedure ?

Hope to receive your reply and Thanks in Advanced.

**Comment by hugovk** [comment]
This is the issue tracker for the [Python Developer’s Guide](https://devguide.python.org/), for people working on [CPython](https://github.com/python/cpython).

Please raise this issue instead with TensorFlow project. Thank you!
